[package]
name = "tgreet"
version = "0.1.0"
edition = "2024"
description = "Terminal greeter that integrates with spotify"
license = "MIT"

[dependencies]
anyhow = "1.0.96"
mpris = "2.0.1"
owo-colors = "4.2.0"

[[bin]]
name = "tgreet"
path = "src/main.rs"
